### PR TITLE
fix(zone): always run in zone for angular micro-frontends

### PR DESCRIPTION
**Pull request by tnicola**
Hi @remackgeek ,

First of all, I would say thanks to you. You saved my life, great work! 

I'm going to open this PR to fix all the cases in which we're importing elements created and defined in a `external Angular micro-frondend`.

**Issue:** Change Detection fails for Angular micro-frontends.

Maybe you're familiar with micro-frondents but for who don't know it's a technique in which a web app is a composition of features which are owned by independent teams (see https://micro-frontends.org/ for more details). 

I tried to replicate a Micro-fronteds architecture in which, there is an Angular `Host` application and some other Angular components (`my-custom-elements`) created via @angular/elements. I'm importing the two elements from here: https://github.com/tnicola/my-custom-element but there's a problem, also with your library the change detection doesn't work for these external elements. This is due to the `NgZone.isInAngularZone()` check done at this line: https://github.com/remackgeek/elements-zone-strategy/blob/a485d15707a4c49eebfdc7c002245fcd75d7e8df/projects/elements-zone-strategy/src/lib/element-zone-strategy.ts#L32 . 

Since we have two 2 Angular apps, the`host` and `my-custom-elements`, there will be also 2 NgZones and 2 ApplicationRefs, each app has it own. So, `isInAngularZone()` will return true for `my-custom-elements` even if we are in the Host NgZone (this is due because for each angular app a zone with 'angular' name is created and isAngularZone checks if there is at least one zone called 'angular'). What we need to get change detection working is to enter in `my-custom-elements` zone. 

Removing the  `NgZone.isInAngularZone()`  check, as suggested in the PR won't break nothing in all the other cases and it would cost zero. If we already are in a zone, re-enter in the same zone is a noop operation.

Let me know if it's clear what I wrote. Thanks!

### CODE REVIEW

**Comment by remackgeek** [comment]
@tnicola , I'm glad someone else found this useful!
A couple of thoughts: 
-  Wouldn't it be simpler to handle the multiple zone issue by pulling out zone.js of your elements and putting it  in your page shell?  Here's my example of that: [angularJSMultipleElementsPOC](https://github.com/remackgeek/angularJSMultipleElementsPOC), based on this article: [How to build REAL Web Components with Angular 6](https://medium.com/@neckster/how-to-build-real-web-components-with-angular-6-ac842c9062dd).
- I am not a zone expert by any means -- I based that "check the zone" pattern from code by people who *do* seem to know zone really well. If you think that change is something you need, you should bring it up in the discussion on this PR: [fix(elements): initialization should run in ngZone (#24181)](https://github.com/angular/angular/pull/24185), and see what the angular folks have to say. This library is based on that PR, which has the same pattern. I'm hoping that PR is the long-term solution.

**Comment by tnicola** [comment]
@remackgeek Thank you for your comments.

- zone.js is imported just once, from the shell project and it's global. My elements are not importing zone.js from polyfills, thanks to ngx-build-plus: https://github.com/manfredsteyer/ngx-build-plus/blob/e94d3346f0b36c11f2d35a141e44fbed392660e2/lib/src/plus/index.ts#L21
 It's not a problem of importing zone.js twice (that would raise an error), it's more a problem of having 2 angular apps, each one with his NgZone service that forks from the root zone. That means having 2 angular zones on the zone stack.

- I'm not a zone expert too :) I've just had a look to the code base, I'll bring the question there then. I hope your solution will be merged too.

**Comment by remackgeek** [comment]
@tnicola, I'm happy to take the change, but I want to keep my simple shell example. If you want to change your PR down to just the code change, I'll do the merge. If you don't want to bother with that, I can just make the change myself. Either way it will probably be a few days until I can get to it.

**Comment by remackgeek** [comment]
Also, you might be interested in this angular bug which is mostly the same issue: [Hosting a Web Component inside an angular app. Data binding and change tracking is not working. #24901](https://github.com/angular/angular/issues/24901)

**Comment by tnicola** [comment]
@remackgeek Thanks! the demo was just to show you the issue and the resolution. I removed the example, the PR is updated.

**Comment by remackgeek** [comment]
@tnicola , I merged your change and published version 6.0.4. I hope it works for you.

**Comment by tnicola** [comment]
@remackgeek It works great! 🎉 Thanks!!

**Pull request merged**
